- README.md
- readme-vars.yml
- root/defaults/nginx.conf
- root/defaults/proxy.conf
http://nginx.org/en/docs/http/websocket.html
Many of our https://github.com/linuxserver/reverse-proxy-confs already include similar headers but not done in the way recommended in the nginx docs. This covers them all with the ability to proxy websockets.
I will create a separate PR to cleanup/adjust proxy samples in that repo.
Edit: https://github.com/linuxserver/reverse-proxy-confs/pull/197 should be merged BEFORE this.
> WebSocket proxying

- readme-vars.yml
- root/defaults/nginx.conf
- root/defaults/proxy.conf
- root/defaults/ssl.conf
Biggest change here is moving `client_body_buffer_size 128k;	# Timeout if the real server is dead` and `send_timeout 5m;` from proxy.conf to nginx.conf. Keeps only proxy related settings in proxy.conf. The rest is just sorting alphabetically for ease of finding what you're looking for.
> Cleanups and reordering

- root/defaults/geoip2.conf
This adds an allow_list variable that you need to use if $allowed_country or $allowed_city `default`is set to no.
Setting `IP/CIDR yes;` does not work.
I got a false positive last time I tested, as I was testing on a CF proxied domain. So my IP was being proxied and I werent accessing the domain through a local ip.
Fixes the current geoip2 setup instructions. 
Closes #19
Tested on my swag setup.
> adds an allow LAN ip list if geoip2 default is no.

- README.md
- readme-vars.yml
- root/defaults/ssl.conf
https://infosec.mozilla.org/guidelines/web_security#x-frame-options
> `X-Frame-Options` has been superseded by the Content Security Policy’s `frame-ancestors` directive, which allows considerably more granular control over the origins allowed to frame a site. As `frame-ancestors` is not yet supported in IE11 and older, Edge, Safari 9.1 (desktop), and Safari 9.2 (iOS), it is recommended that sites employ `X-Frame-Options` in addition to using CSP.
This change is included in an optional header, so not enabled by default.
> Set frame-ancestors in Content-Security-Policy

- root/defaults/dns-conf/transip.ini
Add documentation TransIP DNS plugin file `/swag/config/dns-conf/transip.ini`.
The original text in the `transip.ini` file was unclear. I was not able to generate a wildcard certificate by insufficient instructions in the comments and documentation URL. Finally I discovered that the `transip.key` is a TransIP API key pair. Then it was very easy to use this plugin.
No source changes made, only comments added. Log:
```
swag             | Using Let's Encrypt as the cert provider
swag             | SUBDOMAINS entered, processing
swag …
```
> Add documentation TransIP DNS TXT usage

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
- root/defaults/dns-conf/directadmin.ini
- root/etc/cont-init.d/50-config
This PR adds support for DNS validation with DirectAdmin using plugin https://github.com/cybercinch/certbot-dns-directadmin
Currently it is not possible to perform DNS validation when a domain's DNS records are maintained on a (self-hosted) DirectAdmin instance.
Built the container, pushed to Docker Hub (https://hub.docker.com/r/simonlepla/swag) and tested it on my setup. Worked well (tested custom DNS propagation time as well).
Settings (docker-compose):
```
swag:
image: simonlepla/swag:directadmin
container_name: swag
environment:
- …
```
> Add support for DirectAdmin DNS validation

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
- root/defaults/dns-conf/vultr.ini
- root/etc/cont-init.d/50-config
This change introduces a vultr DNS authentication plugin for certbot.
vultr is a popular VPS provider that supports dynamic dns, this PR may be useful to some of your users.
Running the x86_64 build locally on my vultr instance. Confirmed valid LE certificate has been installed in my container.
In addition to this I have successfully built the arm64 image with the latest upstream docker image.
```
git pull $MY_REPO; cd docker-swag
sudo docker build   --no-cache   --pull   -t ghcr.io/linuxserver/swag:latest .
sudo -u my_user docker run \ …
```
> Add vultr certbot authenticator plugin

- readme-vars.yml
- root/defaults/authelia-location.conf
- root/defaults/authelia-server.conf
This adds newer remote credential information from the auth_request headers sent by Authelia, Remote-Name includes the users display name, and Remote-Email includes their email. Additionally it sets the X-Forwarded-Method header to the original $request_method detected by nginx, which is used for the new acl rule method filter.
Adds the new features of the upstream project (Authelia) to the config templates.
This is tested in integration testing upstream. However this has **NOT** been tested specifically with LSIO's swag image or this …
> feat(authelia): add remote name/email headers and pass http method

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- readme-vars.yml
currently ip6tables legacy requires a missing kernel module, however ip6tables-nft is already included in the image and works as expected.
**Prior to making the change**
```
2021-12-21 13:44:54,350 fail2ban.filter         [609]: INFO    [authelia] Found 2607:fb90:ffff:ff11:4ebc:1234:faf:5803 - 2021-12-21 13:44:54
2021-12-21 13:45:00,558 fail2ban.filter         [609]: INFO    [authelia] Found 2607:fb90:ffff:ff11:4ebc:1234:faf:5803 - 2021-12-21 13:45:00
2021-12-21 13:45:04,563 fail2ban.filter         [609]: INFO    [authelia] Found 2607:fb90:ffff:ff11:4ebc:1234:faf:5803 - 2021-12-21 13:45:04
2021-12-21 13:45:04,907 fail2ban.actions        [609]: NOTICE  [authelia] Ban 2607:fb90:ffff:ff11:4ebc:1234:faf:5803
2021-12-21 13:45:04,977 fail2ban.utils          [609]: ERROR   7f69f9f5dd40 -- exec: …
```
> replace ip6tables legacy with ip6tables-nft due to missing kernel module

- README.md
- readme-vars.yml
- root/defaults/fail2ban/filter.d/nginx-unauthorized.conf
- root/defaults/jail.local
- root/defaults/nginx.conf
- Added a fail2ban jail for nginx unauthorized
- Ignore local subnets in fail2ban to avoid banning the user
Example log message:
`1.2.3.4 - - [09/Jan/2022:17:20:48 +0200] "POST /Users/authenticatebyname HTTP/1.1" 401 36 "-" "Mozilla/5.0 (Android 10; Mobile; rv:91.0) Gecko/91.0 Firefox/91.0"`
```
Status for the jail: nginx-unauthorized
|- Filter
|  |- Currently failed: 1
|  |- Total failed:     1
|  `- File list:        /config/log/nginx/unauthorized.log
```
> Added a fail2ban jail for nginx unauthorized

- readme-vars.yml
- root/etc/cont-init.d/50-config
added code to test for existence of unauthorized.log and create it if not exists.
/config/log/nginx/unauthorized.log is written to by addition of nginx-unauthorized jail in jail.local
- [ x] I have read the [contributing](https://github.com/linuxserver/docker-swag/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications
This fixes a bug where the current image complains repeatedly that it is unable to find the file 'unauthorized.log'
image has been built locally.
> Update 50-config create fail2ban unauthorized.log

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
- root/defaults/dns-conf/dynu.ini
- root/etc/cont-init.d/50-config
* Add Dynu DNS validation via certbot-dns-dynu: https://github.com/bikram990/certbot-dns-dynu to dockerfiles.
* Added 'dynu' to valid dns plugin lists in 50-config and readme-vars.yml
Allow other users with Dynu Dynamic DNS service to utilize this container for their own environments and use cases.
```
sudo docker build --no-cache --pull -t linuxserver/swag:latest .
```
compose file:
```
version: "2.1"
networks:
default:
name: proxynet
services:
nginx:
image: [IMAGE ID of build]
container_name: swag
hostname: swag
cap_add:
- NET_ADMIN …
```
> Add Dynu DNS Support

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
- root/defaults/dns-conf/acmedns-registration.json
- root/defaults/dns-conf/acmedns.ini
- root/etc/cont-init.d/50-certbot
Adding support for using acmedns DNS validation via the certbot-dns-acmedns certbot plug-in.  The plug-in was added from an existing python package (certbot-dns-acmedns) and incorporated via the Dockerfile RUN action (as with the other certbot plug-ins in this image).  Two additional files were added in the dns-conf directory (an INI and a JSON file) to allow for configuration of the plug-in.  
No original code is included in this PR (all code was sourced from existing repositories).
I have incorporated these changes into the docker image I …
> Added acmedns validation plugin for certbot

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
- root/defaults/dns-conf/do.ini
- root/etc/cont-init.d/50-certbot
Adding support for using [DO](https://do.de) (DomainOffensive) DNS validation.
- Add do DNS validation via [certbot-dns-do](https://github.com/georgeto/certbot-dns-do)  to Dockerfiles.
- Added 'do' to valid dns plugin lists in 50-config and readme-vars.yml
- Added 'do.ini' config file to dns-conf directory
Allow other users with DO DNS service to utilize this container for their own environments and use cases.
~~~
sudo docker build --no-cache --pull -t linuxserver/swag:latest .
~~~
compose file:
~~~
---
version: "2.1"
services:
swag:
image: …
> Added do (domainoffensive) validation plugin for certbot. closes #262

- README.md
- readme-vars.yml
- root/app/le-renew.sh
- root/defaults/etc/letsencrypt/renewal-hooks/deploy/10-default
- root/defaults/etc/letsencrypt/renewal-hooks/post/10-nginx
- root/defaults/etc/letsencrypt/renewal-hooks/pre/10-nginx
- root/etc/cont-init.d/40-folders
- root/etc/cont-init.d/50-certbot
This supersedes https://github.com/linuxserver/docker-swag/pull/89
The changes here use the default location that already exists for hooks (`/config/etc/letsencrypt/renewal-hooks`) and remove the suggestions in the documentation for users to make changes.
Essentially, the feature will exist undocumented.
Will need to rebase after https://github.com/linuxserver/docker-swag/pull/169
> Renewal hooks

- README.md
- readme-vars.yml
- root/etc/cont-init.d/50-certbot
Following up from https://github.com/linuxserver/docker-swag/pull/277
Not adding an additional changelog entry since the previous PR includes a changelog entry mentioning the changes, but this PR adjusts the readme to reflect the changes.
Removing information about `duckdns` validation.
It was a custom implementation. It worked fine, but I'm working on making all validation consistent in more ways in the future, so using the `duckdns` plugin fits that goal.
The old duckdns variables are only being removed from the documentation, and `duckdns` is being listed as an option for `DNSPLUGIN`. The old variables will continue to work, the logic is not being removed from the scripts, just translated behind the scenes to work with the plugin.
> Update readme with new duckdns info

- root/etc/cont-init.d/50-certbot
Should allow local DNS records with DuckDNS
Potentially solves https://github.com/linuxserver/docker-swag/issues/292 and https://github.com/linuxserver/docker-swag/issues/281
Needs testing!
> Use --dns-duckdns-no-txt-restore flag

- root/etc/cont-init.d/50-certbot
In addition to https://github.com/linuxserver/docker-baseimage-alpine-nginx/pull/115
I believe removing the self signed cert files and replacing them with symlinks before certbot successfully generates live cert files is causing `15-keygen` in the base to fail because the `if` condition thinks the files don't exist (symlinks do, but the files at the destination of the symlinks do not) so it tries to run `openssl` which fails because it can't write out files to the specified locations because there are symlinks in the way.
The above linked PR to the base should resolve the issue, but this change would also only remove the self signed cert files and replace them with symlinks if the live certs have been successfully generated.
A common case where this makes sense to have a safety check …
> Relocate live cert symlink

- readme-vars.yml
- root/defaults/dns-conf/cpanel.ini
- root/defaults/dns-conf/directadmin.ini
- root/etc/cont-init.d/50-certbot
- Resolves incorrect handling of cpanel dns plugin introduced in https://github.com/linuxserver/docker-swag/pull/277 by using correct new syntax and CLI arguments. Fixes https://github.com/linuxserver/docker-swag/issues/303
- Resolves newly required CLI arguments for directadmin plugin version 1.0.3 (and newer). Fixes https://github.com/linuxserver/docker-swag/issues/307
- Apply string replacements for dns plugin confs to renewal file `/config/etc/letsencrypt/renewal/${ORIGDOMAIN}.conf`, also rearrange script to keep existing string replacements for user config next to string replacements for renewal file. Fixes https://github.com/linuxserver/docker-swag/issues/296
- Move revocation logic up, mostly to keep cert issuing logic and preceding variable assignment closer together.
- Rewrite …
> Revamp certbot init

- root/etc/s6-overlay/s6-rc.d/init-crontabs-config/run
Ref: https://discord.com/channels/354974912613449730/1067391319196053514
Previously the whole `/config/crontabs` folder was copied into `/etc/crontabs`, but we only provided a `root` file by default. Users could add any file name there (not just `root` or `abc`) and it would copy in.
That behavior was changed in https://github.com/linuxserver/docker-swag/pull/315 but the intention wasn't to prevent using cron as `abc`.
It's probably best if we only support `root` and `abc` out of the box.
> Add abc crontab

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
Porkbun was removed in https://github.com/linuxserver/docker-swag/pull/308 to allow upgrading certbot to 2.x. The plugin should now support certbot 2.x.
This closes https://github.com/linuxserver/docker-swag/issues/325
> Add porkbun support back in

- root/defaults/dns-conf/route53.ini
Comments out credentials for AWS Route53
Reason for change - Explicitly providing incorrect credentials to the aws libraries will always result in an unauthorized request. When running on aws, providing no credentials allows the libraries to obtain temporary credentials from aws IMDS when an ec2 instance has assumed a role. 
Commenting these lines out allows the libraries (boto3 in the case of certbot) to function as intended, while still indicating the format of these variables to any reader of this file. 
Benefits users running swag on aws …
> Comment Default Configs

- README.md
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-crontabs-config/run
Should resolve https://github.com/linuxserver/docker-swag/issues/345
> Format cron init and set permissions

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
resolves https://github.com/linuxserver/docker-swag/issues/335
I've been closing these issues and ignoring them in discord as they'rea benign warning, but it doesn't seem like it's much effort to resolve.
currently logs will show `2023-03-29 08:48:35,232 fail2ban.configreader   [515]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'`
this is because by default the line is commented out in the shipped fail2ban. this just sets it to exactly what it's defaulting to. this should eliminate the warning without any change in functionality.
> Silence allowipv6 warning

- root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
- missing -i flag
- use word boundary instead of space
This should resolve https://github.com/linuxserver/docker-swag/issues/397
User in comment confirmed it resolved the issue.
> Fix removing ini values

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
Since v1.0.3 of the certbot-dns-directadmin plugin the parameter prefix was changed to `dns-directadmin-` in stead of `directadmin-`.
This PR addresses this change as the current logic is broken.
Example:
```
root@37e5913fddc8:/# certbot plugins --authenticators
usage:
certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: …
```
> Fix "unrecognized arguments" issue in DirectAdmin DNS plugin

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/defaults/dns-conf/dynu.ini
Document using package install mod for additional plugins
Closes https://github.com/linuxserver/docker-swag/issues/422
> Deprecate certbot-dns-dynu

- root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
> Run package installer as part of SWAG init to prevent init fail due to missing dns plugin

- root/defaults/nginx/authelia-location.conf.sample
- root/defaults/nginx/authelia-server.conf.sample
- root/defaults/nginx/authentik-location.conf.sample
supersedes https://github.com/linuxserver/docker-swag/pull/464
https://github.com/linuxserver/reverse-proxy-confs/pull/656 is not needed.
> support for authelia 4.38+

- README.md
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
It seems zerossl fixed their acme cert revocation and it now works if revoked with just defining the cert and the private key. No EAB necessary.
Tested locally with ZeroSSL and the cert is shown in their dashboard as revoked as well as on crt.sh
Also tested Let's Encrypt to make sure the addition of private key to the revoke arguments didn't break it.
> fix zerossl cert revocation

- root/etc/s6-overlay/s6-rc.d/init-outdated-config/run
- root/migrations/02-swag-old-certbot-paths
> Try and warn about confs looking at /etc for certs

- readme-vars.yml
> Add working link for fail2ban-client manpage

- Dockerfile
- Dockerfile.aarch64
- README.md
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-permissions-config/run
- root/etc/s6-overlay/s6-rc.d/svc-swag-auto-reload/run
- root/etc/s6-overlay/s6-rc.d/svc-swag-auto-reload/type
> Add auto-reload, skip logrotate.status file in log chmod

- root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
Sometimes, though various actions of the user, such as setting DNS validation but not setting a provider, we end up with a cli.ini that contains a:
```
dns--credentials=/config/dns-conf/.ini
```
Instead of a valid provider e.g.:
```
dns-ovh-credentials=/config/dns-conf/ovh.ini
```
And this breaks certbot as it can't find the matching ini file.
So now if that entry exists in the cli.ini we just delete it as it can never be valid.
Closes #546
> Check for broken dns credentials value in cli.ini and remove

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
Refs:
https://eff-certbot.readthedocs.io/en/stable/using.html#log-rotation
https://eff-certbot.readthedocs.io/en/stable/using.html#certbot-command-line-options
https://github.com/certbot/certbot/blob/62361dac442c065005455a0c78ea066fedc6c5f8/certbot/src/certbot/_internal/log.py#L172
Certbot's new log rotate functionality performs a rotation on every run of the `certbot` command. Our init runs the command at least one time (up to 4 times depending on conditional logic), and then `cron` runs daily. I investigated using their built-in log rotate, but it is less ideal to keep logs over time if a container is frequently restarted or updated because this reduces the time period for logs that would be kept by certbot's built in log rotation.
> Disable Certbot's built in log rotation

- .gitignore
- root/defaults/nginx/tinyauth-location.conf.sample
- root/defaults/nginx/tinyauth-server.conf.sample
- root/etc/s6-overlay/s6-rc.d/init-swag-config/run
PR adds tiny auth capabilities
connected to this: https://github.com/linuxserver/reverse-proxy-confs/pull/767
> add tinyauth
