linuxserver/docker-swag

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml
=> Add php7-xsl

readme-vars.yml, root/defaults/default, root/defaults/geoip2.conf, root/defaults/nginx.conf, root/etc/cont-init.d/50-config
Replaced https://github.com/linuxserver/docker-swag/pull/12
=> Geoip2 instructions

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, readme-vars.yml, root/defaults/dns-conf/netcup.ini, root/etc/cont-init.d/50-config
This PR adds support for using the german domain provider [netcup](https://www.netcup.de/) for dns validation.
Todo so, the [certbot-dns-netcup plugin](https://pypi.org/project/certbot-dns-netcup/) has been added.
It will allow all users of the provider netcup to make use of this docker container for requesting wildcard certificates.
I've tested the changes by generating a new wildcard certificate for a domain which is part of my netcup account.
This has been done on amd64 platform.
=> Add support for using provider netcup for DNS validation

readme-vars.yml
Updates the README to mention the `nginx-deny` jail which also exists, and bit me!
I accidentally set `deny all;` in a block, and got locked out. I then discovered this jail by running `docker exec -it nginx fail2ban-client status`
It has not, beyond discovering the jail as mentioned above.
```
[root@Acheron nginx]# docker exec -it nginx fail2ban-client status
Status
|- Number of jail:      4
`- Jail list:   nginx-badbots, nginx-botsearch, nginx-deny, nginx-http-auth
[root@Acheron nginx]# docker exec -it nginx fail2ban-client status …
```
=> Update README with nginx-deny jail

.github/workflows/external_trigger.yml, .github/workflows/external_trigger_scheduler.yml, .github/workflows/package_trigger.yml, .github/workflows/package_trigger_scheduler.yml, README.md, readme-vars.yml, root/defaults/dns-conf/gehirn.ini, root/defaults/dns-conf/sakuracloud.ini, root/etc/cont-init.d/50-config, root/etc/cont-init.d/70-templates
add gehirn and sakuracloud dns validation
add conf checker
add trigger workflows
remove deprecated certbot option for public ip logging
=> add new dns methods, check confs, add workflows

readme-vars.yml, root/defaults/502.html, root/defaults/default, root/defaults/index.html, root/etc/cont-init.d/50-config
Replaced index.html with page with some info, including a link to the swag documentation.
Added http502 helper page, also linking to our docs.
UI suggestions encouraged
Increase the possibility of self-help, decrease support requests
It builds and shows the expected pages
=> Added helpers

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml, root/defaults/dns-conf/hetzner.ini, root/etc/cont-init.d/50-config
=> add support for hetzner dns validation

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, readme-vars.yml
I tested running the install cmd inside the container on `x86-64` and `arm64`
#107 & #108
=> swag: php7-gmp and php7-pecl-mailparse

README.md, readme-vars.yml, root/etc/cont-init.d/50-config
=> fix libmaxminddb updater

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml, root/defaults/dns-conf/ionos.ini, root/etc/cont-init.d/50-config
=> add ionos dns plugin

readme-vars.yml, root/defaults/ssl.conf
Google Federated Learning of Cohorts (FLoC) is a new advertising-surveillance initiative that seeks to replace third-party cookies with a new user profiling technique that garners data generated by the browser itself.
Giving the option to opt out of google floc.
I've verified that the header works.
https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea
=> Add an optional header to opt out of Google FLoC

root/defaults/fail2ban/filter.d/nginx-unauthorized.conf
Ignore plex unauthorized requests
=> Ignore plex unauthorized requests

README.md, readme-vars.yml
- [ X] I have read the [contributing](https://github.com/linuxserver/docker-swag/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications
add nginx unauthorized in Using fail2ban section
=> add nginx unauthorized in Using fail2ban section

Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml
=> fix azure dns

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, readme-vars.yml, root/defaults/dns-conf/godaddy.ini, root/defaults/dns-conf/porkbun.ini, root/etc/cont-init.d/50-certbot
Supersedes https://github.com/linuxserver/docker-swag/pull/264
Closes https://github.com/linuxserver/docker-swag/issues/208
=> Certbot dns

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml, root/app/duckdns-txt, root/defaults/dns-conf/cpanel.ini, root/defaults/dns-conf/duckdns.ini, root/defaults/dns-conf/gandi.ini, root/defaults/dns-conf/infomaniak.ini, root/etc/cont-init.d/50-certbot
- Update cpanel and gandi dns plugin handling
- Switch to certbot-dns-duckdns
=> Dns updates

.github/workflows/external_trigger.yml, Jenkinsfile, README.md, jenkins-vars.yml, readme-vars.yml
=> Pin certbot to 1.32.0 until plugin compatibility improves

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, readme-vars.yml
=> Pin acme to certbot version

.github/workflows/call_invalid_helper.yml, Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml, root/defaults/dns-conf/cloudxns.ini, root/etc/cont-init.d/50-certbot
=> Remove defunct cloudxns plugin

readme-vars.yml
Edit: Removing variables entirely. This can be merged at any time.
=> Fix variable names

root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
=> Replace even older service location

README.md, readme-vars.yml, root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
=> Cleanup unused csr and keys folders

README.md, readme-vars.yml, root/defaults/etc/letsencrypt/renewal-hooks/post/10-nginx, root/etc/s6-overlay/s6-rc.d/init-certbot-config/run
=> Fix renewal post hook

README.md, readme-vars.yml, root/defaults/nginx/authelia-location.conf.sample, root/defaults/nginx/authentik-location.conf.sample, root/defaults/nginx/site-confs/default.conf.sample
[Move ssl.conf include to default.conf](https://github.com/linuxserver/docker-swag/pull/364/commits/43a7239fbf8f105aeac59e175e7028840e1c271a)
[Remove Authorization headers in authelia](https://github.com/linuxserver/docker-swag/pull/364/commits/7a831681c5ca57e16a746653bf7b8fc30fb3dfcb)
[Sort proxy_set_header in authelia and authentik](https://github.com/linuxserver/docker-swag/pull/364/commits/7a831681c5ca57e16a746653bf7b8fc30fb3dfcb)
Closes https://github.com/linuxserver/docker-swag/issues/360
Closes …
=> ssl.conf include and authelia authorization changes

root/defaults/fail2ban/filter.d/nginx-unauthorized.conf
Closes https://github.com/linuxserver/docker-swag/issues/374
=> Remove broken fail2ban plex regex

Dockerfile, Dockerfile.aarch64, README.md, readme-vars.yml, root/defaults/dns-conf/namecheap.ini
Closes https://github.com/linuxserver/docker-swag/issues/405
=> Add Namecheap DNS plugin

Dockerfile, Dockerfile.aarch64, README.md, readme-vars.yml
=> remove stream.conf

Dockerfile, Dockerfile.aarch64, README.md, jenkins-vars.yml, readme-vars.yml, root/defaults/dns-conf/google-domains.ini, root/defaults/nginx/site-confs/default.conf.sample
Merge https://github.com/linuxserver/reverse-proxy-confs/pull/681 first.
Related but this PR does not depend on https://github.com/linuxserver/docker-baseimage-alpine-nginx/pull/170
=> Rebase to 3.20

readme-vars.yml
Should really be following RFC6761
=> Add cap description, use example.com/org/net

root/migrations/02-swag-old-certbot-paths
=> Migrate existing renewal confs with old paths

README.md, readme-vars.yml
=> Update auto reload wording
